services:
  webshop:
    image: ${DOCKER_REGISTRY-}webshop
    build:
      context: .
      dockerfile: WebShop/Dockerfile
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
        - .env
    volumes:
        - ./db-data/:/var/lib/postgresql/data/
